/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedResumesIndexRouteImport } from './routes/_authenticated/resumes/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedResumesNewRouteImport } from './routes/_authenticated/resumes/new'
import { Route as AuthenticatedResumesIdRouteImport } from './routes/_authenticated/resumes/$id'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees/new'
import { Route as AuthenticatedEmployeesIdRouteImport } from './routes/_authenticated/employees/$id'
import { Route as AuthenticatedEmployeesIdImportRouteImport } from './routes/_authenticated/employees/$id_.import'
import { Route as AuthenticatedResumesIdVariantsIndexRouteImport } from './routes/_authenticated/resumes/$id_/variants/index'
import { Route as AuthenticatedResumesIdHistoryIndexRouteImport } from './routes/_authenticated/resumes/$id_/history/index'
import { Route as AuthenticatedResumesIdEditIndexRouteImport } from './routes/_authenticated/resumes/$id_/edit/index'
import { Route as AuthenticatedResumesIdCompareIndexRouteImport } from './routes/_authenticated/resumes/$id_/compare/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumesIndexRoute =
  AuthenticatedResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumesNewRoute = AuthenticatedResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumesIdRoute = AuthenticatedResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIdRoute =
  AuthenticatedEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIdImportRoute =
  AuthenticatedEmployeesIdImportRouteImport.update({
    id: '/employees/$id_/import',
    path: '/employees/$id/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumesIdVariantsIndexRoute =
  AuthenticatedResumesIdVariantsIndexRouteImport.update({
    id: '/resumes/$id_/variants/',
    path: '/resumes/$id/variants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumesIdHistoryIndexRoute =
  AuthenticatedResumesIdHistoryIndexRouteImport.update({
    id: '/resumes/$id_/history/',
    path: '/resumes/$id/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumesIdEditIndexRoute =
  AuthenticatedResumesIdEditIndexRouteImport.update({
    id: '/resumes/$id_/edit/',
    path: '/resumes/$id/edit/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumesIdCompareIndexRoute =
  AuthenticatedResumesIdCompareIndexRouteImport.update({
    id: '/resumes/$id_/compare/',
    path: '/resumes/$id/compare/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/resumes/new': typeof AuthenticatedResumesNewRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/resumes/': typeof AuthenticatedResumesIndexRoute
  '/employees/$id/import': typeof AuthenticatedEmployeesIdImportRoute
  '/resumes/$id/compare/': typeof AuthenticatedResumesIdCompareIndexRoute
  '/resumes/$id/edit/': typeof AuthenticatedResumesIdEditIndexRoute
  '/resumes/$id/history/': typeof AuthenticatedResumesIdHistoryIndexRoute
  '/resumes/$id/variants/': typeof AuthenticatedResumesIdVariantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/resumes/new': typeof AuthenticatedResumesNewRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/resumes': typeof AuthenticatedResumesIndexRoute
  '/employees/$id/import': typeof AuthenticatedEmployeesIdImportRoute
  '/resumes/$id/compare': typeof AuthenticatedResumesIdCompareIndexRoute
  '/resumes/$id/edit': typeof AuthenticatedResumesIdEditIndexRoute
  '/resumes/$id/history': typeof AuthenticatedResumesIdHistoryIndexRoute
  '/resumes/$id/variants': typeof AuthenticatedResumesIdVariantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/_authenticated/resumes/new': typeof AuthenticatedResumesNewRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/resumes/': typeof AuthenticatedResumesIndexRoute
  '/_authenticated/employees/$id_/import': typeof AuthenticatedEmployeesIdImportRoute
  '/_authenticated/resumes/$id_/compare/': typeof AuthenticatedResumesIdCompareIndexRoute
  '/_authenticated/resumes/$id_/edit/': typeof AuthenticatedResumesIdEditIndexRoute
  '/_authenticated/resumes/$id_/history/': typeof AuthenticatedResumesIdHistoryIndexRoute
  '/_authenticated/resumes/$id_/variants/': typeof AuthenticatedResumesIdVariantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/employees/$id'
    | '/employees/new'
    | '/resumes/$id'
    | '/resumes/new'
    | '/employees/'
    | '/resumes/'
    | '/employees/$id/import'
    | '/resumes/$id/compare/'
    | '/resumes/$id/edit/'
    | '/resumes/$id/history/'
    | '/resumes/$id/variants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/employees/$id'
    | '/employees/new'
    | '/resumes/$id'
    | '/resumes/new'
    | '/employees'
    | '/resumes'
    | '/employees/$id/import'
    | '/resumes/$id/compare'
    | '/resumes/$id/edit'
    | '/resumes/$id/history'
    | '/resumes/$id/variants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login/'
    | '/_authenticated/employees/$id'
    | '/_authenticated/employees/new'
    | '/_authenticated/resumes/$id'
    | '/_authenticated/resumes/new'
    | '/_authenticated/employees/'
    | '/_authenticated/resumes/'
    | '/_authenticated/employees/$id_/import'
    | '/_authenticated/resumes/$id_/compare/'
    | '/_authenticated/resumes/$id_/edit/'
    | '/_authenticated/resumes/$id_/history/'
    | '/_authenticated/resumes/$id_/variants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumes/': {
      id: '/_authenticated/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AuthenticatedResumesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/new': {
      id: '/_authenticated/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof AuthenticatedResumesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/$id': {
      id: '/_authenticated/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AuthenticatedResumesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/$id': {
      id: '/_authenticated/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/$id_/import': {
      id: '/_authenticated/employees/$id_/import'
      path: '/employees/$id/import'
      fullPath: '/employees/$id/import'
      preLoaderRoute: typeof AuthenticatedEmployeesIdImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/$id_/variants/': {
      id: '/_authenticated/resumes/$id_/variants/'
      path: '/resumes/$id/variants'
      fullPath: '/resumes/$id/variants/'
      preLoaderRoute: typeof AuthenticatedResumesIdVariantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/$id_/history/': {
      id: '/_authenticated/resumes/$id_/history/'
      path: '/resumes/$id/history'
      fullPath: '/resumes/$id/history/'
      preLoaderRoute: typeof AuthenticatedResumesIdHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/$id_/edit/': {
      id: '/_authenticated/resumes/$id_/edit/'
      path: '/resumes/$id/edit'
      fullPath: '/resumes/$id/edit/'
      preLoaderRoute: typeof AuthenticatedResumesIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resumes/$id_/compare/': {
      id: '/_authenticated/resumes/$id_/compare/'
      path: '/resumes/$id/compare'
      fullPath: '/resumes/$id/compare/'
      preLoaderRoute: typeof AuthenticatedResumesIdCompareIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEmployeesIdRoute: typeof AuthenticatedEmployeesIdRoute
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedResumesIdRoute: typeof AuthenticatedResumesIdRoute
  AuthenticatedResumesNewRoute: typeof AuthenticatedResumesNewRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedResumesIndexRoute: typeof AuthenticatedResumesIndexRoute
  AuthenticatedEmployeesIdImportRoute: typeof AuthenticatedEmployeesIdImportRoute
  AuthenticatedResumesIdCompareIndexRoute: typeof AuthenticatedResumesIdCompareIndexRoute
  AuthenticatedResumesIdEditIndexRoute: typeof AuthenticatedResumesIdEditIndexRoute
  AuthenticatedResumesIdHistoryIndexRoute: typeof AuthenticatedResumesIdHistoryIndexRoute
  AuthenticatedResumesIdVariantsIndexRoute: typeof AuthenticatedResumesIdVariantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEmployeesIdRoute: AuthenticatedEmployeesIdRoute,
  AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
  AuthenticatedResumesIdRoute: AuthenticatedResumesIdRoute,
  AuthenticatedResumesNewRoute: AuthenticatedResumesNewRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedResumesIndexRoute: AuthenticatedResumesIndexRoute,
  AuthenticatedEmployeesIdImportRoute: AuthenticatedEmployeesIdImportRoute,
  AuthenticatedResumesIdCompareIndexRoute:
    AuthenticatedResumesIdCompareIndexRoute,
  AuthenticatedResumesIdEditIndexRoute: AuthenticatedResumesIdEditIndexRoute,
  AuthenticatedResumesIdHistoryIndexRoute:
    AuthenticatedResumesIdHistoryIndexRoute,
  AuthenticatedResumesIdVariantsIndexRoute:
    AuthenticatedResumesIdVariantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
