/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as EmployeeNewRouteImport } from './routes/employee/new'
import { Route as EmployeeIdRouteImport } from './routes/employee/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNewRoute = EmployeeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeIdRoute = EmployeeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/employee/': typeof EmployeeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/employee': typeof EmployeeIndexRoute
  '/login': typeof LoginIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/employee/': typeof EmployeeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee/$id'
    | '/employee/new'
    | '/employee/'
    | '/login/'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee/$id' | '/employee/new' | '/employee' | '/login' | '/test'
  id:
    | '__root__'
    | '/'
    | '/employee/$id'
    | '/employee/new'
    | '/employee/'
    | '/login/'
    | '/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/new': {
      id: '/employee/new'
      path: '/new'
      fullPath: '/employee/new'
      preLoaderRoute: typeof EmployeeNewRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/$id': {
      id: '/employee/$id'
      path: '/$id'
      fullPath: '/employee/$id'
      preLoaderRoute: typeof EmployeeIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
