/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments/index'
import { Route as ResumesIdRouteImport } from './routes/resumes/$id'
import { Route as EmployeeNewRouteImport } from './routes/employee/new'
import { Route as EmployeeIdRouteImport } from './routes/employee/$id'
import { Route as AssignmentsNewRouteImport } from './routes/assignments/new'
import { Route as AssignmentsIdRouteImport } from './routes/assignments/$id'
import { Route as ResumesIdEditRouteImport } from './routes/resumes/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIdRoute = ResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeNewRoute = EmployeeNewRouteImport.update({
  id: '/employee/new',
  path: '/employee/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIdRoute = EmployeeIdRouteImport.update({
  id: '/employee/$id',
  path: '/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsNewRoute = AssignmentsNewRouteImport.update({
  id: '/assignments/new',
  path: '/assignments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIdRoute = AssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIdEditRoute = ResumesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ResumesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/resumes/$id': typeof ResumesIdRouteWithChildren
  '/assignments/': typeof AssignmentsIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/test/': typeof TestIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/resumes/$id': typeof ResumesIdRouteWithChildren
  '/assignments': typeof AssignmentsIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/login': typeof LoginIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/test': typeof TestIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/employee/$id': typeof EmployeeIdRoute
  '/employee/new': typeof EmployeeNewRoute
  '/resumes/$id': typeof ResumesIdRouteWithChildren
  '/assignments/': typeof AssignmentsIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/test/': typeof TestIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments/$id'
    | '/assignments/new'
    | '/employee/$id'
    | '/employee/new'
    | '/resumes/$id'
    | '/assignments/'
    | '/employee/'
    | '/login/'
    | '/resumes/'
    | '/test/'
    | '/resumes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments/$id'
    | '/assignments/new'
    | '/employee/$id'
    | '/employee/new'
    | '/resumes/$id'
    | '/assignments'
    | '/employee'
    | '/login'
    | '/resumes'
    | '/test'
    | '/resumes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/assignments/$id'
    | '/assignments/new'
    | '/employee/$id'
    | '/employee/new'
    | '/resumes/$id'
    | '/assignments/'
    | '/employee/'
    | '/login/'
    | '/resumes/'
    | '/test/'
    | '/resumes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsIdRoute: typeof AssignmentsIdRoute
  AssignmentsNewRoute: typeof AssignmentsNewRoute
  EmployeeIdRoute: typeof EmployeeIdRoute
  EmployeeNewRoute: typeof EmployeeNewRoute
  ResumesIdRoute: typeof ResumesIdRouteWithChildren
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$id': {
      id: '/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof ResumesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/new': {
      id: '/employee/new'
      path: '/employee/new'
      fullPath: '/employee/new'
      preLoaderRoute: typeof EmployeeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$id': {
      id: '/employee/$id'
      path: '/employee/$id'
      fullPath: '/employee/$id'
      preLoaderRoute: typeof EmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/new': {
      id: '/assignments/new'
      path: '/assignments/new'
      fullPath: '/assignments/new'
      preLoaderRoute: typeof AssignmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$id': {
      id: '/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AssignmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$id/edit': {
      id: '/resumes/$id/edit'
      path: '/edit'
      fullPath: '/resumes/$id/edit'
      preLoaderRoute: typeof ResumesIdEditRouteImport
      parentRoute: typeof ResumesIdRoute
    }
  }
}

interface ResumesIdRouteChildren {
  ResumesIdEditRoute: typeof ResumesIdEditRoute
}

const ResumesIdRouteChildren: ResumesIdRouteChildren = {
  ResumesIdEditRoute: ResumesIdEditRoute,
}

const ResumesIdRouteWithChildren = ResumesIdRoute._addFileChildren(
  ResumesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsIdRoute: AssignmentsIdRoute,
  AssignmentsNewRoute: AssignmentsNewRoute,
  EmployeeIdRoute: EmployeeIdRoute,
  EmployeeNewRoute: EmployeeNewRoute,
  ResumesIdRoute: ResumesIdRouteWithChildren,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
