/**
 * TanStack Router instance.
 *
 * The route tree is generated by TanStack Router's file-based codegen
 * (via the TanStackRouterVite Vite plugin in dev mode, or via
 * `npm run routes:generate` manually). Do NOT import the route tree from
 * this file; import `routeTree` from `./route-tree.gen' if needed elsewhere.
 */
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./route-tree.gen";

export const router = createRouter({ routeTree });

// Register the router instance for full type safety across the app.
// See: https://tanstack.com/router/latest/docs/framework/react/guide/type-safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
